apiVersion: batch/v1
kind: CronJob
metadata:
  name: mysql-backup
  # namespace: production
spec:
  schedule: "1 * * * *" # Daily at 2 AM
  successfulJobsHistoryLimit: 7
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: mysql-backup
          containers:
            - name: backup
              image: alpine:latest
              command:
                - /bin/sh
                - -c
                - |
                  # Install dependencies (fast on Alpine)
                  apk add --no-cache mysql-client aws-cli bash

                  # Fail if any command in a pipe fails
                  set -o pipefail

                  TIMESTAMP=$(date +%Y%m%d_%H%M%S)
                  BACKUP_FILE="/backup/mysql_backup_${TIMESTAMP}.sql.gz"

                  echo "Starting backup to ${BACKUP_FILE}..."
                  # Added --skip-ssl to avoid self-signed cert errors
                  mysqldump -h mysql.default.svc.cluster.local \
                    -uroot -p${MYSQL_ROOT_PASSWORD} \
                    --all-databases \
                    --single-transaction \
                    --quick \
                    --events \
                    --routines \
                    --triggers \
                    --skip-ssl \
                    --lock-tables=false | gzip > ${BACKUP_FILE}

                  if [ $? -eq 0 ]; then
                    echo "Backup successful! Uploading to S3..."
                    aws s3 cp ${BACKUP_FILE} s3://my-tf-demo-harish-bucket-2025/mysqlbackup/
                    
                    if [ $? -eq 0 ]; then
                       echo "S3 Upload successful!"
                    else
                       echo "S3 Upload failed!"
                       exit 1
                    fi

                    # Keep only last 30 days locally
                    find /backup -name "mysql_backup_*.sql.gz" -mtime +30 -delete
                  else
                    echo "Backup failed!"
                    exit 1
                  fi
              env:
                - name: MYSQL_ROOT_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: mysql-root-secret
                      key: password
              envFrom:
                - secretRef:
                    name: aws-credentials
              volumeMounts:
                - name: backup-storage
                  mountPath: /backup
          volumes:
            - name: backup-storage
              persistentVolumeClaim:
                claimName: mysql-backup-pvc
          restartPolicy: OnFailure
