apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  # namespace: production
  labels:
    app: mysql
    tier: database
    environment: production
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      tier: database

  template:
    metadata:
      labels:
        app: mysql
        tier: database
        environment: production
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9104" # MySQL exporter

    spec:
      # Anti-affinity to spread across nodes (for HA)
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - mysql
                topologyKey: kubernetes.io/hostname

      securityContext:
        fsGroup: 999

      # Init container for permissions
      initContainers:
        - name: init-mysql
          image: busybox:1.35
          command:
            - sh
            - -c
            - |
              chown -R 999:999 /var/lib/mysql
          securityContext:
            runAsUser: 0
            runAsNonRoot: false
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql

      containers:
        - name: mysql
          image: harishnshetty/mysql:100 # Your signed image
          imagePullPolicy: IfNotPresent

          args:
            - --default-authentication-plugin=mysql_native_password
            - --max-connections=500
            - --innodb-buffer-pool-size=512M
            - --slow-query-log=1
            - --long-query-time=2

          ports:
            - name: mysql
              containerPort: 3306
              protocol: TCP

          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-root-secret
                  key: password
            - name: MYSQL_DATABASE
              value: webappdb
            - name: TZ
              value: "UTC"

          securityContext:
            runAsUser: 999
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false # MySQL needs to write
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE # For port 3306

          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "2000m"
              memory: "2Gi"

          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
              subPath: mysql
            - name: mysql-config
              mountPath: /etc/mysql/conf.d
              readOnly: true
            - name: mysql-init-script
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true

          livenessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3

        # Sidecar: MySQL Exporter for Prometheus
        # helm search repo prometheus-community
        # Using latest version matching prometheus-community/prometheus-mysql-exporter chart
        - name: mysql-exporter
          image: prom/mysqld-exporter:v0.17.2
          ports:
            - name: metrics
              containerPort: 9104
          args:
            - --config.my-cnf=/etc/mysql_exporter/.my.cnf
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
          volumeMounts:
            - name: mysql-exporter-config
              mountPath: /etc/mysql_exporter
              readOnly: true

      volumes:
        - name: mysql-config
          configMap:
            name: mysql-config
        - name: mysql-init-script
          configMap:
            name: mysql-init-script
        - name: mysql-exporter-config
          secret:
            secretName: mysql-exporter-secret

  volumeClaimTemplates:
    - metadata:
        name: mysql-data
        labels:
          app: mysql
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: gp2 # Available in cluster
        resources:
          requests:
            storage: 1Gi # Production size

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  # namespace: production
  labels:
    app: mysql
spec:
  type: ClusterIP
  clusterIP: None # Headless service
  selector:
    app: mysql
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
    - name: metrics
      port: 9104
      targetPort: 9104
