apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harishshetty-tls
  namespace: gateway
spec:
  secretName: harishshetty-tls

  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer

  dnsNames:
    - "*.harishshetty.xyz"
    - "harishshetty.xyz"
# watch kubectl get certificate -n gateway
# kubectl get secret harishshetty-tls -n gateway
