apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: prod
type: Opaque
data:
  username: cm9vdA== #root
  password: cGFzc3dvcmQ= #password
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ= #password
  MYSQL_REPL_PASSWORD: cGFzc3dvcmQ= #password
