apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: check-vulnerabilities
  namespace: prod
spec:
  validationFailureAction: Enforce
  webhookTimeoutSeconds: 30
  failurePolicy: Fail
  rules:
    - name: not-older-than-1-week
      match:
        any:
          - resources:
              kinds:
                - Pod
                - Deployment
      verifyImages:
        - imageReferences:
            - "*"
          attestors:
            - count: 1
              entries:
                - keys:
                    publicKeys: |-
                      -----BEGIN PUBLIC KEY-----
                      MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE2waGwj98vsapDzDi/6PoBHnyY0EC
                      TjzxYJsoB17qti0QPHUzVhShvRPZxF5sOFzS3voQLtfyYvCxJT3dTwWiUg==
                      -----END PUBLIC KEY-----

          attestations:
            - type: https://cosign.sigstore.dev/attestation/vuln/v1
              conditions:
                - all:
                    - key: "{{ time_since('','{{ predicate.metadata.scanFinishedOn }}', '') }}"
                      operator: LessThanOrEquals
                      value: "168h"
