apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kibana-route
  namespace: default
spec:
  parentRefs:
    - name: external-gateway
      namespace: gateway
      sectionName: https
  hostnames:
    - kibana.harishshetty.xyz
  rules:
    - backendRefs:
        - kind: Service
          name: kibana-kibana
          namespace: elk
          port: 5601
