apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harishshetty-tls
  namespace: nginx-gateway
spec:
  secretName: harishshetty-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "*.harishshetty.xyz"
  dnsNames:
    - "*.harishshetty.xyz"
