apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-route53
spec:
  acme:
    email: harishn662@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory # Staging server
    # server: https://acme-v02.api.letsencrypt.org/directory   # Production service
    privateKeySecretRef:
      name: letsencrypt-route53
    solvers:
      - selector:
          dnsZones:
            - harishshetty.xyz
            - "*.harishshetty.xyz"
        dns01:
          route53:
            region: ap-south-1
