apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-to-https-redirect
  namespace: nginx-gateway
spec:
  parentRefs:
    - name: my-gateway
      sectionName: http
  hostnames:
    - "nginx.harishshetty.xyz"
    - "httpd.harishshetty.xyz"
    - "*.harishshetty.xyz"
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
