apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager
  namespace: cert-manager
  annotations:
    # Replace with the actual IAM role ARN from Terraform output
    # Run: terraform output cert_manager_role_arn
    eks.amazonaws.com/role-arn: "arn:aws:iam::970378220457:role/cert-manager-iam-role"
