apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: elk-selfsigned-issuer
  namespace: elk
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: elasticsearch-cert
  namespace: elk
spec:
  secretName: elasticsearch-master-certs
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - elasticsearch-master
    - elasticsearch-master.elk
    - elasticsearch-master.elk.svc
    - elasticsearch-master.elk.svc.cluster.local
  issuerRef:
    name: elk-selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
