apiVersion: kyverno.io/v1
# kind: ClusterPolicy
kind: Policy
metadata:
  name: check-vulnerabilities
  namespace: db
spec:
  validationFailureAction: Enforce
  background: false
  webhookTimeoutSeconds: 30
  failurePolicy: Fail
  rules:
    - name: checking-vulnerability-scan-not-older-than-one-hour
      match:
        any:
          - resources:
              kinds:
                - Pod
      verifyImages:
        - imageReferences:
            - "*"
          attestations:
            - type: https://cosign.sigstore.dev/attestation/vuln/v1
              conditions:
                - all:
                    - key: "{{ time_since('','{{ metadata.scanFinishedOn }}', '') }}"
                      operator: LessThanOrEquals
                      value: "1h"
              attestors:
                - count: 1
                  entries:
                    - keys:
                        publicKeys: |-
                          -----BEGIN PUBLIC KEY-----
                          MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEUZEMIux1EooUmuEXHqO3BNeJJrOj
                          MvexirBUU56iT0PyKNkFaIoaCtKEoX3QIOVNdrGSWUl6DcYQfURGzVbAVQ==
                          -----END PUBLIC KEY-----
