apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: test-deny
  namespace: db
spec:
  validationFailureAction: Enforce
  background: false
  rules:
    - name: deny-all
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "Denying all pods for testing"
        deny: {}
