apiVersion: v1
kind: Namespace
metadata:
  name: elk
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-root-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: elk-root-ca
  namespace: elk
spec:
  isCA: true
  commonName: elk-root-ca
  secretName: elk-root-ca-secret
  duration: 87600h # 10y
  privateKey:
    algorithm: RSA
    size: 2048
  issuerRef:
    name: selfsigned-root-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: elk-issuer
  namespace: elk
spec:
  ca:
    secretName: elk-root-ca-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: elasticsearch-cert
  namespace: elk
spec:
  secretName: elk-tls-certs
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - elasticsearch-master
    - elasticsearch-master.elk
    - elasticsearch-master.elk.svc
    - elasticsearch-master.elk.svc.cluster.local
    - localhost
  issuerRef:
    name: elk-issuer
    kind: Issuer
    group: cert-manager.io
